export const ADD_FLASH_MESSAGE= 'ADD_FLASH_MESSAGE';
export const DELETE_FLASH_MESSAGE= 'DELETE_FLASH_MESSAGE';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const GET_PUBLIC_DOCUMENTS = 'GET_PUBLIC_DOCUMENTS';
export const GET_DOCUMENT = 'GET_DOCUMENT';
export const CREATE_DOCUMENT = 'CREATE_DOCUMENT';
